### ISSUE TITLE
Game not working pls fix

### ISSUE THREAD

**Issue by Mambabosso** [BenjaminBrandtner/dinoSpiel#6]
When i tried the game, some errors occurred. PLS FIX!!!!!!

**Comment by BenjaminBrandtner** [comment]
Dear Mr. Mambabosso

We are sorry for any inconvenience we have caused you. We are already aware of certain bugs present in our program.  
As we knew you to be quite a critical and diligent programmer, we naturally expected some constructive criticism and perhaps some proposed solutions. It appears we were sorely mistaken in our judgement of your character and politely request that you do not contact us again.

Best Regards
